In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [12]:
%%time
import pandas as pd

CPU times: total: 0 ns
Wall time: 0 ns


In [13]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [14]:
type(np.array(my_list))

numpy.ndarray

In [15]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [24]:
np.random.rand(6)

array([0.31658281, 0.87294264, 0.56841908, 0.39436592, 0.30509604,
       0.13152468])

In [25]:
np.random.rand(6,6)

array([[0.23534624, 0.39062374, 0.67569013, 0.59346401, 0.68570311,
        0.11547504],
       [0.55422572, 0.03683645, 0.86051844, 0.62297542, 0.00653357,
        0.66389226],
       [0.2374465 , 0.52283347, 0.49229665, 0.20134526, 0.88106447,
        0.86407061],
       [0.66234007, 0.01234294, 0.98497602, 0.36878012, 0.03364801,
        0.1155714 ],
       [0.17562726, 0.58858424, 0.61596123, 0.56613127, 0.65668469,
        0.6586241 ],
       [0.03351627, 0.41168113, 0.16136867, 0.87492363, 0.87314212,
        0.24045378]])

In [26]:
arr= np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
import numpy as np
ranarr=np.random.randint(1,50,10)
print(ranarr)
arr.reshape(5,5)

[ 7 46 13 33 41  3 24 26 31 15]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
import numpy as np
ranarr=np.random.randint(1,50,10)
print(ranarr)
arr.reshape(5,5)

[22 47 10 24  5  4 36 46 23 31]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.max()

24

In [31]:
arr.min()

0

In [32]:
import numpy as np
median_value = np.median(arr)
print("Array:", arr)
print("Median value:", median_value)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Median value: 12.0


In [33]:
arr[1:5]

array([1, 2, 3, 4])

In [34]:
arr[0:5]=100

In [35]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# Pandas library in python

In [73]:
import pandas as pd

In [74]:
mca=pd.read_csv("homeprices1.csv")
mca

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

mca.head()

In [59]:
mca.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [60]:
mca.tail()

area  bedrooms  age   price
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [61]:
mca.iloc[[0,1]]

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000

In [62]:
mca.iloc[[2,3]]

area  bedrooms  age   price
2  3200       NaN   18  610000
3  3600       3.0   30  595000

In [63]:
mca.shape

(6, 4)

In [64]:
del mca["area"]

In [65]:
mca

bedrooms  age   price
0       3.0   20  550000
1       4.0   15  565000
2       NaN   18  610000
3       3.0   30  595000
4       5.0    8  760000
5       6.0    8  810000

In [66]:
del mca["age"]

In [67]:
mca

bedrooms   price
0       3.0  550000
1       4.0  565000
2       NaN  610000
3       3.0  595000
4       5.0  760000
5       6.0  810000

In [68]:
mca.filter(["price","bedrooms"])

price  bedrooms
0  550000       3.0
1  565000       4.0
2  610000       NaN
3  595000       3.0
4  760000       5.0
5  810000       6.0

In [69]:
mca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   bedrooms  5 non-null      float64
 1   price     6 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 224.0 bytes


In [70]:
mca=mca.dropna()
mca

bedrooms   price
0       3.0  550000
1       4.0  565000
3       3.0  595000
4       5.0  760000
5       6.0  810000

In [75]:
mca=mca.dropna(inplace = True )
mca

In [76]:
mca

In [79]:
import pandas as pd

# Example initialization
data = {'profit': [100, 200, 300]}
mca = pd.DataFrame(data)


In [80]:
print(mca.head())


   profit
0     100
1     200
2     300


In [82]:
mca = pd.read_csv('homeprices1.csv')
mca


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [83]:
import pandas as pd

# Example data
data = {'profit': [100, 200, 300]}
mca = pd.DataFrame(data)

# Check if mca is initialized correctly
if mca is not None:
    # Calculate the mean of the profit column
    mean_profit = mca["profit"].mean()
    print("Mean profit:", mean_profit)
else:
    print("mca is None")


Mean profit: 200.0


In [84]:
mca['profit'].median()

200.0

In [85]:
mca['profit'].max()

300

In [86]:
mca['profit'].min()

100

In [5]:
import pandas as pd

# Example data to create the DataFrame
data = {
    'age': ['25', '30', 'thirty-five', '40', '45'],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
}

# Creating the DataFrame
mca = pd.DataFrame(data)

# Converting 'age' to numeric, coercing errors
mca['age'] = pd.to_numeric(mca['age'], errors='coerce')

print(mca)


    age     name
0  25.0    Alice
1  30.0      Bob
2   NaN  Charlie
3  40.0    David
4  45.0      Eva
